/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stocksmonitor;

import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;

import org.json.JSONArray;
import org.json.JSONObject;

public class App {

  public static void main(String[] args) {
    var client = HttpClient.newHttpClient();

    String[] symbols = { "MGLU3", "PETR4", "RRRP3", "BBAS3" };

    String apiKey = "";
    long begin = System.currentTimeMillis();

    for (String symbol : symbols) {
      var request = HttpRequest.newBuilder(
          URI.create(
              "https://brapi.dev/api/quote/" + symbol + "?token=" + apiKey))
          .header("accept", "application/json")
          .build();

      HttpResponse<String> response;
      try {
        System.out.println(symbol);

        response = client.send(request, HttpResponse.BodyHandlers.ofString());
        JSONObject jsonObject = new JSONObject(response.body());

        JSONArray stockData = jsonObject.getJSONArray("results");
        var a = stockData.getJSONObject(0).get("regularMarketPrice");
      } catch (IOException e) {
        e.printStackTrace();
      } catch (InterruptedException e) {
        e.printStackTrace();
      }
    }
    long end = System.currentTimeMillis();

    long time = end - begin;
    System.out.println();
    System.out.println("Elapsed Time: " + time + " milli seconds");

    begin = System.currentTimeMillis();

    Thread[] threads = new Thread[symbols.length];

    for (int i = 0; i < symbols.length; i++) {
      Thread t = new Thread(new Symbol(symbols[i]));
      threads[i] = t;
      t.start();
    }

    try {
      for (Thread thread : threads) {
        thread.join();
      }
    } catch (InterruptedException e) {
      e.printStackTrace();
    }

    end = System.currentTimeMillis();
    time = end - begin;
    System.out.println();
    System.out.println("Elapsed Time: " + time + " milli seconds");
  }
}
