/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stocksmonitor;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.Timer;
import java.util.TimerTask;

public class AppTest {

  public static void main(String[] args) {
    Set<String> symbols = new HashSet<>();
    symbols.add("MGLU3");
    symbols.add("PETR4");
    symbols.add("RRRP3");
    symbols.add("BBAS3");

    Timer timer = new Timer();

    Map<String, Float> stockPrices = new HashMap<>();

    int scheduleTimeout = 30000;

    TimerTask task = new TimerTask() {
      public void run() {
        System.out.println("Execução do scheduler");
        StockPriceSearcher searcher = new StockPriceSearcher(symbols, stockPrices);

        searcher.updateStockPrices();
      }
    };
    timer.scheduleAtFixedRate(task, 0, scheduleTimeout);
  }
}
